---
title: "Mergint the KHP datasets"
author: "Marco Barandun"
date: "`r Sys.Date()`"
output: html_document
---

Here I am going to merge the datasets of Kampmann, Hohl and Peter.

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
# Loading the necessary libraries
library(tidyverse)
library(lubridate)

library(mapview)
library(sf)
library(sp)

source("/Users/marco/GitHub/GitHub_G4B/2023_re-survey/3_scripts/config_1_readVegedaz_marco.R")
```

# Dorothea Kampmann

## Vegetation plots

```{r}

dv <- readVegedaz("/Users/marco/GitHub/GitHub_G4B/2023_re-survey/1_original_data/Data_Dorothea_Kampmann/NFP48_C_Vegetationsaufnahmen.tab")

dv$samp <- dv$samp %>%
  # Mutating everything to character to avoid issues
  mutate(across(everything(), as.character)) %>%
  
  # Renaming variables
  rename(
    slope = "Gef.lle_grad",
    exposition = "Exposition....",
    author = BearbeiterIn,
    date = Datum,
    elevation = "H.he_dhm",
    y_coord = Y_coord,
    x_coord = X_coord
  ) %>%
  
  # Set the order of the variables
  select(
    x_coord, y_coord, elevation, date, author,
    slope, exposition
  ) %>%
  
  # Creating new column with rowname in it
  setDT(., keep.rownames = TRUE) %>%
  
  # Fixing small date issues and other data cleaning
  mutate(
    year = as.numeric(str_sub(date, -4, -1)),
    taxon = "Tracheophyta",
    origin = "dorothea_pflanzen",
    
    issues = as.character(NA),
    year = if_else(rn == "TUOE05", 2002, year),
    date = if_else(rn == "TUOE05", "24-06-2002", date),
    issues = if_else(rn == "TUOE05", "date", issues)
    
  ) %>%
  
  # Dropping rows with insufficient data
  drop_na(year, date, x_coord, y_coord) %>%
  
  # Standardize date across datasets
  mutate(date = parse_date_time(date, orders = c("dmy")))
```

Let's inspect the dataset.

```{r}

# Data structure
head(dv$samp)
head(dv$xtab[, 1:5])

# Display interactive map
mapview(st_as_sf(dv$samp, coords = c("x_coord", "y_coord"), crs = 21781), cex = 3)
```

# Markus Peter

## Vegetation plots

```{r}
peter_grindelwald <- readVegedaz("/Users/marco/GitHub/GitHub_G4B/2023_re-survey/1_original_data/Data_Markus_Peter_ART-Datenbank/Peter_Grindelwald_ART-Datenbank.tab")
#peter_sent <- readVegedaz("/Users/marco/GitHub/GitHub_G4B/2023_re-survey/1_original_data#/Data_Markus_Peter_ART-Datenbank/Peter_Sent_ART-Datenbank.tab") 
peter_tujetsch <- readVegedaz("/Users/marco/GitHub/GitHub_G4B/2023_re-survey/1_original_data/Data_Markus_Peter_ART-Datenbank/Peter_Tujetsch_ART-Datenbank.tab")


# Grindelwald
peter_grindelwald$samp <- peter_grindelwald$samp %>%
  mutate(across(everything(), as.character)) %>%
  # Renaming variables using a named vector for clarity
  rename(
    exposition = "Exposition....",
    x_coord = "X_Koordinate",
    y_coord = "Y_Koordinate",
    slope = "Neigung....",
    elevation = "H.he..m...M..",
    author = "Autor.der.Vegetationsaufnahme",
    date = "Datum"
  ) %>%
  # Dropping rows without coordinates (assuming x_coord and y_coord are numeric)
  filter(!is.na(x_coord) & !is.na(y_coord)) %>%
  filter(x_coord != "n.a.") %>%
  # Selecting only the variables present in the other datasets
  select(
    x_coord, y_coord, elevation, date,
    author, slope, exposition, Nummer_Autor, Vegetationsgruppe, everything()
  )

# Tujetsch
peter_tujetsch$samp <- peter_tujetsch$samp %>%
  mutate(across(everything(), as.character)) %>%
  # Renaming variables using a named vector for clarity
  rename(
    exposition = "Exposition....",
    x_coord = "X_Koordinate",
    y_coord = "Y_Koordinate",
    slope = "Neigung....",
    elevation = "H.he..m...M..",
    author = "Autor.der.Vegetationsaufnahme",
    date = "Datum"
  ) %>%
  # Dropping rows without coordinates (assuming x_coord and y_coord are numeric)
  filter(!is.na(x_coord) & !is.na(y_coord)) %>%
  filter(x_coord != "n.a.") %>%
  # Selecting only the variables present in the other datasets
  select(
    x_coord, y_coord, elevation, date,
    author, slope, exposition, Nummer_Autor, Vegetationsgruppe, everything()
  )

pv <- rbind(
  peter_grindelwald$samp[, 1:9],
  peter_tujetsch$samp[, 1:9]
) %>%
  
  
  # Identifying NAs
  mutate_all(~replace(., . == "n.a.", NA)) %>%
  mutate_all(~replace(., . == "-", NA)) %>%
  
  rename(plotID = Nummer_Autor,
         LU1980 = Vegetationsgruppe) %>%
  
  # Creating new columns
  mutate(year = as.numeric(str_sub(.$date,-4,-1)),
         taxon = "Tracheophyta",
         origin = "peter_pflanzen",
         #across(c(x_coord, y_coord, slope, elevation), as.numeric),
         
         issues = as.character(NA),
         LU2000 = NA) %>%

  # Creating new column with rowname in it
  setDT(., keep.rownames = TRUE) %>%
  
  # Fixing small issues
  mutate(issues = if_else(date == "Grindelwald.353", "year", issues),
         year = if_else(rn == "Grindelwald.353", 1980, year),
         issues = if_else(date == "Tujetsch.230", "year", issues),
         year = if_else(rn == "Tujetsch.230", 2003, year),
         
         issues = if_else(date == "Juni 1981", "date", issues),
         date = if_else(date == "Juni 1981", "15.06.1981", date),
         issues = if_else(date == "Juli 1981", "date", issues),
         date = if_else(date == "Juli 1981", "15.07.1981", date),
         issues = if_else(date == "August 1981", "date", issues),
         date = if_else(date == "August 1981", "15.08.1981", date),
         issues = if_else(date == "September 1981", "date", issues),
         date = if_else(date == "September 1981", "15.09.1981", date)) %>%
  
  # Standardize date across datasets
  mutate(date = lubridate::parse_date_time(.$date, orders = c("dmy", "y"))) %>%
  
  # Note down issues encountered
  mutate(issues = if_else(endsWith(as.character(.$date), "-01-01"), "date", issues)) %>%
  
  # Dropping columns with insufficient data
  drop_na(year, x_coord, y_coord)





```

```{r}
# Create a mapping of cardinal degrees to their corresponding numeric representations
exposition_mapping <- c("N" = 0, "NNE" = 22.5, "NE" = 45, "ENE" = 67.5,
                        "E" = 90, "ESE" = 112.5, "SE" = 135, "SSE" = 157.5,
                        "S" = 180, "SSW" = 202.5, "SW" = 225, "WSW" = 247.5,
                        "W" = 270, "WNW" = 292.5, "NW" = 315, "NNW" = 337.5)

# Use mutate and replace the exposition values with numeric representations if they are not already numeric
df <- df %>%
  mutate(exposition_numeric = ifelse(is.na(as.numeric(exposition)), 
                                     sapply(strsplit(exposition, ""), function(dir) sum(exposition_mapping[dir])),
                                     as.numeric(exposition)))
```
